/** content_b_en.js — chapters 6–10 and references of the English W1 monograph. */
const path = require("path");
const FIG = path.resolve(__dirname, "..", "..", "monograph", "en", "figures");

module.exports = [

// ════════════════════════════════════════════ Chapter 6
{ type: "h1", text: "6. Wave model II: time domain with unit-cell truncation (E7)" },
{ type: "h2", text: "6.1. The naive nondispersive model is ill-posed" },
{ type: "p", text: "The frequency-domain model of chapter 5 is indefinitely-indefinite: the tensor μ = diag(1, −η) is assumed frequency-independent. Taken literally as a time-domain initial-value problem, the model loses well-posedness: modes with ω² = c²(k_{y}² − k_{x}²/η) < 0 grow exponentially. On the grid the fastest unstable mode sits near the Nyquist k_{x}: the discrete growth rate is" },
{ type: "formula", num: "6.1", markup: "*γ*_{max} = 2/(Δ*x*·√*η*)," },
{ type: "p", text: "which amounts to 51 time-units⁻¹ at η = 100 and Δx = 1/255 — the field accumulates dozens of e-folds per unit time and the numerical solution explodes within a fraction of a unit (the E7c control, section 6.7). This is not a grid artifact but a property of the continuum model: the unbounded growth of |k| at a fixed frequency is incompatible with passivity. Real hyperbolic metamaterials are dispersive — and this dispersion is mandatory." },
{ type: "h2", text: "6.2. Drude regularisation and unconditional well-posedness" },
{ type: "p", text: "We model the negative constituent by the response of a wire-mesh metamaterial — the Drude form" },
{ type: "formula", num: "6.2", markup: "*μ*_{y}(*ω*) = 1 − *ω*_{p}^{2}/*ω*^{2}," },
{ type: "p", text: "where the plasma frequency is set by the unit cell: ω_p = πc/a, a = L/N being the cell size and N the number of cells across the chamber. Introducing an auxiliary polarisation field χ, the problem reduces to the two-field system" },
{ type: "formula", num: "6.3", markup: "*E*_{tt} = *c*^{2}(Δ*E* + ∂_{x}*χ*) − *σE*_{t}," },
{ type: "formula", num: "6.4", markup: "*χ*_{tt} = −*ω*_{p}^{2}(*χ* + ∂_{x}*E*) − *σχ*_{t}." },
{ type: "p", text: "The dispersion of this system is quadratic in Ω = ω²:" },
{ type: "formula", num: "6.5", markup: "Ω^{2} − *c*^{2}*S*Ω + *c*^{2}*k*_{y}^{2}*ω*_{p}^{2} = 0,   *S* = *ω*_{p}^{2}/*c*^{2} + *k*_{x}^{2} + *k*_{y}^{2}," },
{ type: "p", text: "with the discriminant" },
{ type: "formula", num: "6.6", markup: "*c*^{4}[*k*_{x}^{2} + (*k*_{y} − *ω*_{p}/*c*)^{2}][*k*_{x}^{2} + (*k*_{y} + *ω*_{p}/*c*)^{2}] ≥ 0." },
{ type: "p", text: "Both roots are real and non-negative at ANY k: the dispersive system is unconditionally well-posed, exactly as passivity demands. The lower branch below ω_p is hyperbolic; the upper one approaches the usual elliptic limit as ω >> ω_p. A lossless, source-free control evolution preserves the field maximum with a ratio of 1.00 over 8000 steps — a direct demonstration of well-posedness (the naive model explodes under identical conditions, section 6.7)." },
{ type: "h2", text: "6.3. Exact correspondence with the ray model" },
{ type: "p", text: "At a fixed drive frequency ω₀ < ω_p the medium (6.2) is EXACTLY equivalent to the indefinitely-hyperbolic medium of the ray model with the effective anisotropy" },
{ type: "formula", num: "6.7", markup: "*η*_{eff} = (*ω*_{p}/*ω*₀)^{2} − 1   ⟺   *ω*₀ = *ω*_{p}/√(*η* + 1)." },
{ type: "p", text: "Thus η = 100, adopted in all ray experiments, corresponds to ω₀/ω_p = 1/√101 ≈ 0.0995, and the unit cell enters through ω_p: the arm of the iso-frequency hyperbola at a fixed frequency folds back at |k_{x}| ≈ ω_p/c — the cascade terminates at the cell scale (the Brillouin fold), the time-domain analogue of the cascade termination observed in the experiment. The cell truncation here is not a numerical device but a physical parameter: the scan over N (section 6.6) varies exactly this." },
{ type: "h2", text: "6.4. The ADE-FDTD scheme" },
{ type: "p", text: "System (6.3)–(6.4) is integrated with an explicit leapfrog scheme: the fields E and χ and their velocities live on integer steps; the Laplacian and ∂_{x} are central differences with a Dirichlet halo (PEC); outside the chamber the fields are zeroed by a mask. The time step dt = 0.3·Δx/c is stable for the whole coupled system (the maximum grid frequency belongs to the elliptic branch at the Nyquist). The drive is a «soft» source: an acceleration applied at five nodes of a vertical antenna with a Gaussian envelope four drive periods wide (Q ≈ 13, ~4% bandwidth). The loss σ = 0.01 is identical for the hyperbolic medium and the controls." },
{ type: "h2", text: "6.5. E7a: pulsed drive — the funnel and the cascade in real time" },
{ type: "p", text: "The main run: N = 128 cells (256×256 grid, two nodes per cell), ω_p = 402.1, ω₀ = 40.01, η_eff = 100.0 — exactly the medium of the ray experiments; λ₀ = 0.157 (6.4 wavelengths across the chamber, 20 nodes per wavelength). A narrowband pulse is injected by a vertical antenna at (0.5; 0.60) and then evolves freely at σ = 0.01; the analysis window is ballistic, t ≤ 40." },
{ type: "p", text: "Snapshots of |E|² show how the hyperbolic medium channels the pulse into vertical corridors coinciding with the ray route, while the isotropic control (ω_p = 0 — the same chamber, the same pulse) produces uniform speckle (Fig. 6.1, top). The share of the pulse energy inside the route corridor (a ±0.04 band around the ray loop) is systematically higher for the hyperbolic medium; at t = 24 the capture ratio is 1.43 (0.0508 versus 0.0355 for the control); the rapid rise to the plateau takes t ≈ 0.8 — a few cavity crossings." },
{ type: "fig", path: FIG + "/11_time_domain.png", caption: "Fig. 6.1. E7a. Top (left to right): hyperbolic medium at t = 6 and t = 40; isotropic control at t = 40; the ray route is shown in cyan. Bottom: corridor energy fraction F(t) for both media; the k-space spectrum at t = 24 with the overlaid iso-frequency contour (red dashed); the k_{x}-marginals at t = 3 and t = 40 with the ω_p/c fold marked." },
{ type: "p", text: "k-space gives a direct image of the cascade: the spectral weight is locked onto the arms of the iso-frequency hyperbola (the overlay in Fig. 6.1 — an essentially perfect match) and spreads along them over time from |k_{x}| ≈ 100 to |k_{x}| ≈ 170, staying orders of magnitude below the fold |k_{x}| ≈ ω_p/c = 400. The accumulated cascade front |k_{x}|₉₉ (the 99th percentile of the marginal) monotonically saturates: 156 → 169 → 163. Together this is the time-domain realisation of the «cascade along the hyperbola until the cell termination» mechanism." },
{ type: "h2", text: "6.6. E7b: the truncation scan — homogenisation convergence of the attractor" },
{ type: "p", text: "At a fixed η_eff = 100 the drive frequency scales with the cell count: ω₀ = πN/(c·√101), and the number of hyperbolic wavelengths across the chamber grows as N/(2·√101). The scan N ∈ {32, 48, 64, 96, 128, 192} covers the range from 1.6 to 9.6 wavelengths across the chamber (the grid is two nodes per cell, up to 384×384). The peak share of energy inside the route corridor grows monotonically tenfold — from 0.0149 at N = 32 to 0.1525 at N = 192 (Table 6.1, Fig. 6.2a): in the wave model the attractor exists only to the extent the chamber is homogeneous at the route scale. At N = 32 (fewer than two wavelengths across) the cavity cannot express the route at all — the capture stays at the background level; for N ≥ 96 the curve enters a flat regime consistent with the empirical requirement of «several wavelengths per route feature»." },
{ type: "table",
  caption: "Table 6.1. E7b: peak corridor capture versus the number of cells (η_eff = 100 fixed).",
  headers: ["Cells N", "Wavelengths across chamber", "Peak corridor fraction", "Contrast to corridor area"],
  colPct: [18, 30, 28, 24],
  rows: [
    ["32", "1.59", "0.0149", "×0.10"],
    ["48", "2.39", "0.0250", "×0.16"],
    ["64", "3.18", "0.0373", "×0.24"],
    ["96", "4.78", "0.0648", "×0.41"],
    ["128", "6.37", "0.1011", "×0.64"],
    ["192", "9.55", "0.1525", "×0.97"],
  ],
},
{ type: "fig", path: FIG + "/12_truncation.png", caption: "Fig. 6.2. E7. (a) Peak corridor capture versus the number of cells (log-log); annotations — wavelengths across the chamber. (b) The cascade front |kₓ|₉₉ over time in the main run: saturation well below the IFC fold (ω_p/c) and the grid Nyquist." },
{ type: "h2", text: "6.7. E7c: the control — blow-up of the naive model" },
{ type: "p", text: "The control run reproduces the naive nondispersive model (section 6.1) in the same chamber at η = 100 from a localised initial perturbation, without source or loss. The energy grows exponentially; the rate measured over the late window is γ = 74.6, between the discrete estimate 2/(Δx·√η) = 51.0 and the continuum Nyquist value π/(Δx·√η) = 80.1 — consistent with the growth of the fastest unstable lattice mode plus the leapfrog amplification; the blow-up occurs at t ≈ 0.44. The dispersive model under identical conditions remains bounded (the field-maximum ratio 1.00). The «blow-up/bounded» pair closes the argument: time-domain modelling of a hyperbolic cavity must include the dispersion of the negative constituent, and it is exactly this dispersion that carries the cell truncation." },

// ════════════════════════════════════════════ Chapter 7
{ type: "h1", text: "7. Companion: the Aharonov–Bohm effect with water waves" },
{ type: "p", text: "The thematic companion of W1 (ab_water.py) reproduces the wave analogue of the Aharonov–Bohm effect for surface waves in a vortex-filled tank — the problem realised experimentally on water (Berry 1980; OIST, Communications Physics 2026). Scattering on a vortex of circulation α adds a geometric phase: the field is expressed through Bessel functions of fractional order J_|m−α|, which requires a regularised kernel near the origin (we use a kernel with a small order offset). The resulting rotating nodal patterns and the phase winding W(α) are measured for pairs of opposite circulations." },
{ type: "p", text: "Key observations: the winding is exactly antisymmetric, W(−α) = −W(α) to machine precision; the fit gives W(α) = sign(α)·(1.4 + |α|); the mirror correlation of the intensity pair equals 1.0; the rotation sense of the nodal pattern flips with the sign of α. The companion demonstrates that geometric phases are a common language of the «cloud» research series — the same class of phenomena as the route chirality of E3, with a phase instead of a trajectory." },
{ type: "fig", path: FIG + "/08_ab_water.png", caption: "Fig. 7.1. AB companion. Left and centre: rotating nodal patterns of ψ_total for α = +0.3 and α = −0.3 (at t = T/8). Right: the phase winding W(|α|) for both circulation signs; the exact antisymmetry W(−α) = −W(α)." },

// ════════════════════════════════════════════ Chapter 8
{ type: "h1", text: "8. Python ↔ Julia cross-verification" },
{ type: "h2", text: "8.1. The ray core" },
{ type: "p", text: "The Julia port (wave_attractors.jl, standard library only, Julia ≥ 1.10) repeats the ray core operation by operation, including the deterministic corner rules. Two levels are checked: short-horizon identity — 1200 bounce points over a ray ensemble, maximum deviation 3.45·10⁻¹⁵ (machine level); and the statistical equivalence of long trajectories — lock fractions (0.9167 in both languages), period sets ({22}) and the log₁₀|k| sets coincide. Determinism is mandatory: long chaotic transients diverge exponentially under any rounding discrepancy, so the only honest protocol is short horizons plus statistics." },
{ type: "h2", text: "8.2. The E7 TD kernel" },
{ type: "p", text: "For the new time-domain experiments the ADE-FDTD kernel is also ported (td_check.jl) and compared: 400 steps on a 48×48 grid from a fixed Gaussian initial condition, field dumps at steps 0/100/200/300/400, a pointwise comparison against the numpy replica. The maximum relative deviation is 2.4·10⁻¹⁵; the two kernels are machine-level equivalent. The entire chain of results of chapters 3–6 is thus twice independent of the implementation." },
{ type: "fig", path: FIG + "/09_cross_verification.png", caption: "Fig. 8.1. Ray-core cross-verification: maximum deviations of bounce points Python ↔ Julia per ray (circles) against the 10⁻⁸ tolerance and the K = 1 ↔ K = 7 frequency-invariance level." },
{ type: "table",
  caption: "Table 8.1. Cross-verification summary.",
  headers: ["Check", "Deviation", "Protocol"],
  colPct: [40, 26, 34],
  rows: [
    ["Ray core, short trajectories", "**3.45·10⁻¹⁵**", "1200 bounce points"],
    ["Ray statistics of long trajectories", "identical", "lock 0.9167; periods {22}"],
    ["E7 TD kernel (Drude ADE-FDTD)", "**2.4·10⁻¹⁵**", "400 steps, 48×48 grid"],
    ["Frequency invariance of the ray map", "0.0 (exact)", "K = 1 vs K = 7, 1201 bounces"],
  ],
},

// ════════════════════════════════════════════ Chapter 9
{ type: "h1", text: "9. Reproducibility" },
{ type: "h2", text: "9.1. Layout and pipeline" },
{ type: "p", text: "The study lives in the wave_attractors/ directory of the repository: scripts/ (the ray core, experiments E1–E7, the wave models, the AB companion, the Julia ports, the verifiers, the figure generator with --lang en|ru switches), data/ (primary CSV/JSON/NPZ), figures/ (12 figures, 300 dpi), monograph/ru and monograph/en (this monograph in the two language editions with separate figure sets), report/ (the W1 report), and an English README. Everything generated is reproduced from sources by a single command." },
{ type: "pFlat", text: "make wave-attractors        # full protocol (E1–E7 + waves + AB + figures)", opts: { left: 567 } },
{ type: "pFlat", text: "make wave-attractors-quick  # reduced CI protocol", opts: { left: 567 } },
{ type: "pFlat", text: "make wave-attractors-julia  # Julia port + cross-verification (rays and TD)", opts: { left: 567, after: 160 } },
{ type: "h2", text: "9.2. Continuous integration and artifacts" },
{ type: "p", text: "The workflow .github/workflows/wave-attractors.yml triggers on changes to wave_attractors/** and runs two jobs: python-pipeline (core self-tests, reduced E1–E7, AB, reference dumps; the w1-data artifact) and julia-cross-verification (the port + the TD kernel + both verifiers; the w1-cross-verification artifact with cross_verification.json and td_cross_verification.json). The primary data of the new experiments: E6_eta_scan.csv, E6_summary.json, E6_wave_scan.npz; E7_td_snapshots.npz, E7_route_fraction.csv, E7_kspectra.npz, E7_truncation_scan.csv, E7_summary.json. Each data file is self-sufficient to reproduce the corresponding figure without re-running the heavy simulations." },

// ════════════════════════════════════════════ Chapter 10
{ type: "h1", text: "10. Discussion and conclusions" },
{ type: "h2", text: "10.1. Main findings" },
{ type: "pList", text: "**The attractor is an effect of the material.** In the same chamber the hyperbolic medium captures 24 of 24 rays, the isotropic one — none (E2); the cascade, chirality and frequency invariance are reproduced (E1, E3, E4)." },
{ type: "pList", text: "**The attractor window is universal.** Both boundaries of the attractor phase collapse onto the variable u = s·√η across two decades of η: u₁ = 0.176 ± 0.041, u₂ = 0.490 ± 0.084 (E6); the naive resonance s* = 1/√η overestimates the window by a factor of two." },
{ type: "pList", text: "**Well-posedness requires dispersion.** The time-domain problem for the nondispersive indefinite tensor blows up (γ ≈ 2/(Δx·√η)); the Drude metamaterial μ_y(ω) = 1 − ω_p²/ω² makes it unconditionally well-posed and carries the physical cell truncation ω_p = πc/a (E7c)." },
{ type: "pList", text: "**Exact model correspondence.** At ω₀ = ω_p/√(η+1) the TD medium is equivalent to η_eff = 100 of the ray model; the pulsed drive shows the capture funnel (1.43× the control), the cascade on the IFC hyperbola and the saturation of the front below the ω_p/c fold (E7a)." },
{ type: "pList", text: "**Homogenisation convergence.** The peak corridor capture grows monotonically tenfold from 32 to 192 cells (E7b) — the attractor is expressible by the wave only at a sufficient number of cells per route." },
{ type: "pList", text: "**Dual reproducibility.** The whole chain is implemented twice (Python, Julia) with machine-level agreement: 3.45·10⁻¹⁵ over trajectories and 2.4·10⁻¹⁵ over the TD field." },
{ type: "h2", text: "10.2. Limitations" },
{ type: "p", text: "The ray model describes the geometrical-acoustics limit; diffraction effects at slopes and corners are not included. The Drude form is the simplest passive realisation of the negative constituent: a real wire-mesh medium has anisotropic spatial dispersion and logarithmic correction factors in ω_p(a). The wave runs use grids up to 384×384 and moderate Q-factors; the fine structure of the cascade near the fold is investigated phenomenologically (the |k_{x}|₉₉ front) rather than by an exact spectral solution of the scattering problem. Finally, the capture metric is sensitive to the chosen corridor width (±0.04); the relative hyperbolic-versus-control comparisons do not depend on that choice." },
{ type: "h2", text: "10.3. Prospects" },
{ type: "p", text: "Natural continuations are: a spectral verification of the hyperbola fold (comparing the numerical IFC of the discrete medium with (6.5)–(6.6)); TD simulations with the full band structure of the wire-mesh lattice instead of the effective medium; diffraction corrections to the ray law; an experimental η scan on acoustic hyperlens metasurfaces. A separate direction is the connection between the E6 attractor window and the classification of the billiard's periodic orbits: near the upper boundary u₂ the routes lose stability, and the collapse u₂(η) provides a non-trivial test for the perturbation theory of the reflection law (2.4)–(2.5)." },
{ type: "p", text: "In summary: hyperbolic wave attractors are reproduced at two description levels and in two implementation languages, their parametric phenomenology is established by the anisotropy scan, and the time-domain simulation with a physically consistent unit-cell truncation closes the numerical picture onto the real metamaterial. The package is fully reproducible and ready for extension." },

// ════════════════════════════════════════════ References
{ type: "h1", text: "References" },
{ type: "pList", text: "[1] Hyperbolic wave attractors // Nature Physics (2026), CUNY Advanced Science Research Center. DOI: 10.1038/s41567-026-03453-7." },
{ type: "pList", text: "[2] V krivoy kamere volny sami vystroilis v idealnuyu strukturu // Naked Science, 30.09.2026 (popular account of the reference experiment, in Russian)." },
{ type: "pList", text: "[3] Poddubny A., Iorsh I., Belov P., Kivshar Y. Hyperbolic metamaterials // Nature Photonics. 2013. Vol. 7. P. 948–957." },
{ type: "pList", text: "[4] Silveirinha M. G., Engheta N. Design of matched zero-index metamaterials using nonmagnetic inclusions in epsilon-near-zero media // Physical Review B. 2007. Vol. 75. 075119." },
{ type: "pList", text: "[5] Berry M. V. Exact Aharonov–Bohm wavefunction obtained by applying Dirac's magnetic phase factor // European Journal of Physics. 1980. Vol. 1. P. 240–244." },
{ type: "pList", text: "[6] Aharonov–Bohm effect for water waves: vortex-induced geometric phase // Communications Physics (2026), OIST (water-tank experiment)." },
{ type: "pList", text: "[7] Yee K. S. Numerical solution of initial boundary value problems involving Maxwell's equations in isotropic media // IEEE Transactions on Antennas and Propagation. 1966. Vol. 14, No. 3. P. 302–307." },
{ type: "pList", text: "[8] Taflove A., Hagness S. C. Computational Electrodynamics: The Finite-Difference Time-Domain Method. 3rd ed. Boston: Artech House, 2005." },
{ type: "pList", text: "[9] Hofstadter D. R. Energy levels and wave functions of Bloch electrons in rational and irrational magnetic fields // Physical Review B. 1976. Vol. 14. P. 2239–2249." },
{ type: "pList", text: "[10] Bezanson J., Edelman A., Karpinski S., Shah V. B. Julia: A fresh approach to numerical computing // SIAM Review. 2017. Vol. 59, No. 1. P. 65–98." },
{ type: "pList", text: "[11] AB-Cloud Research: the research repository (the AB-Cloud series, study W1). URL: https://github.com/wild8highlander/ab-cloud-research (accessed October 2026)." },
{ type: "pList", text: "[12] Virtual Region: AB_Cloud Monograph v22 (the repository's monograph series, RU/EN/ZH) — the layout template of this edition." },
];
