/** content_a_en.js — chapters 1–5 of the English W1 monograph. */
const path = require("path");
const FIG = path.resolve(__dirname, "..", "..", "monograph", "en", "figures");

module.exports = [

// ════════════════════════════════════════════ Chapter 1
{ type: "h1", text: "1. Introduction" },
{ type: "h2", text: "1.1. Physical context" },
{ type: "p", text: "Hyperbolic metamaterials — media whose principal components of the effective-response tensor have opposite signs — have turned, over the last two decades, from a theoretical curiosity into a practical instrument of wave-field control. Their defining property is that the iso-frequency surface ceases to be an ellipse and opens into a hyperbola: at a fixed frequency the medium supports an infinite continuum of wave vectors, while the energy flux is confined to a narrow cone around the optical axis. This property underlies the hyperlens, sub-diffraction imaging and the modification of spontaneous emission." },
{ type: "p", text: "The paper «Hyperbolic wave attractors» (Nature Physics, 2026, CUNY Advanced Science Research Center) reported a qualitatively new manifestation of the same geometry: waves launched into a cavity of complex shape made of a hyperbolic metamaterial do not scatter chaotically but organise themselves into closed, reproducible, chiral and broadband trajectories — wave attractors. A popular account of the experiment, emphasising its «oceanic» mechanics (shallow slopes, a directional cone, a wavelength cascade), was published by Naked Science on 30 September 2026. The reference study highlights three signatures of the phenomenon: robustness to initial conditions, insensitivity to the drive frequency, and the termination of the cascade at the unit-cell scale of the metamaterial." },
{ type: "p", text: "The phenomenology is as follows. Reflection from an inclined wall in a hyperbolic medium is non-specular: the tangential component of the wave vector is conserved, while the normal component is given by the second root of the dispersion quadratic (the Vieta root). Each such reflection jumps the wave vector along the hyperbola branch, increasing its magnitude — this is the wavelength cascade. In a cavity where inclined walls combine with vertical ones (for which the reflection is specular), the cascade funnels every launched ray onto one and the same closed route; the termination of the cascade at the cell scale produces the observed «ideal structure» of fine caustics." },
{ type: "h2", text: "1.2. Place within the AB-Cloud repository" },
{ type: "p", text: "The AB-Cloud Research repository hosts numerical studies at the intersection of spectral theory, wave physics and metamaterials; every study is packaged as a self-contained module with primary data, scripts, figures, documentation and continuous integration. This monograph documents study W1 — «Hyperbolic wave attractors: numerical reproduction study» — in its extended edition, which includes the two blocks requested after the first release: the scan over the anisotropy strength η (experiment E6) and the time-domain simulation with unit-cell truncation (experiment E7)." },
{ type: "p", text: "The principles inherited from the repository are threefold. First, dual-language reproducibility: all key computations have independent implementations in Python (numpy/scipy) and Julia (standard library only), and the agreement is verified automatically. Second, number traceability: every quantity in the text traces back to a named experiment and a primary data file. Third, honest controls: each effect is accompanied by a null hypothesis (isotropic medium, nondispersive model, etc.)." },
{ type: "h2", text: "1.3. Structure of the monograph" },
{ type: "p", text: "Chapter 2 formalises the physics: dispersion, group-velocity cone, non-specular reflection, cascade and the resonance scale. Chapter 3 describes the ray model and experiments E1–E5. Chapter 4 is devoted to the anisotropy scan E6 and the universality of the attractor window. Chapter 5 describes the frequency-domain wave model; chapter 6 — the time-domain model with unit-cell truncation, including the proof of unconditional well-posedness of the dispersive problem. Chapters 7 and 8 contain the companion study of the water-wave Aharonov–Bohm effect and the Python ↔ Julia cross-verification protocol. Chapter 9 documents reproducibility; chapter 10 discusses the results, limitations and prospects." },

// ════════════════════════════════════════════ Chapter 2
{ type: "h1", text: "2. Physics of hyperbolic wave attractors" },
{ type: "h2", text: "2.1. Indefinite dispersion and the group-velocity cone" },
{ type: "p", text: "We use the TE-like scalar polarisation of a two-dimensional anisotropic medium with the magnetic-permeability tensor μ = diag(1, −η), η > 0. The dispersion relation reads" },
{ type: "formula", num: "2.1", markup: "*k*_{y}^{2} − *k*_{x}^{2}/*η* = *K*^{2},   *K* = *ω*/*c*," },
{ type: "p", text: "so the iso-frequency surface is a hyperbola opening along ±y with two branches (the sign of k_{y}). The group velocity is normal to the iso-frequency surface:" },
{ type: "formula", num: "2.2", markup: "*v*_{g} ∝ (−*k*_{x}/*η*,  *k*_{y})," },
{ type: "p", text: "and therefore the energy flux is confined to a cone of half-angle" },
{ type: "formula", num: "2.3", markup: "*α*_{max} = arctan(1/√*η*)" },
{ type: "p", text: "around the optical axis (the y-axis): at η = 100 the half-angle is 5.71°. This is the defining property of a hyperbolic medium — «waves propagate only along narrow prescribed directions». Importantly, the wave vector and the energy-flux direction generally differ in such a medium: the ray travels along v_{g}, not along k. The ray state is the pair (position, k on the iso-frequency hyperbola)." },
{ type: "fig", path: FIG + "/01_chambers_and_cone.png", caption: "Fig. 2.1. Left: the hexagonal study chamber and the closed attractor route (period 22). Right: the dispersion hyperbola (2.1) and the group-velocity cone (2.3) with a 5.71° half-angle at η = 100." },
{ type: "h2", text: "2.2. Wall reflection: the Vieta roots" },
{ type: "p", text: "Let (t, n) be the orthonormal wall basis (tangent, inward normal). Translational invariance along the wall conserves the tangential component k_{t}. The decomposition k = k_{t}·t + k_{n}·n turns the dispersion into a quadratic equation for k_{n}:" },
{ type: "formula", num: "2.4", markup: "*A k*_{n}^{2} + *B k*_{n} + *C* = 0," },
{ type: "formula", num: "2.5", markup: "*A* = *n*_{y}^{2} − *n*_{x}^{2}/*η*,   *B* = 2*k*_{t}(*t*_{y}*n*_{y} − *t*_{x}*n*_{x}/*η*),   *C* = *k*_{t}^{2}(*t*_{y}^{2} − *t*_{x}^{2}/*η*) − *K*^{2}." },
{ type: "p", text: "The incident wave is one root; the reflected one is the other — the exact reflection law («the other Vieta root»). This reflection is generally non-specular: mirror symmetry is broken by the material, and it is precisely the non-specularity that gives rise to the attractor mechanism. In the isotropic control (μ = 1, circular iso-frequency contour) the equation degenerates to the familiar k_{n} → −k_{n}. Because the incident wave lies on the iso-frequency contour, the discriminant is non-negative for any wall orientation: reflection in a hyperbolic medium never becomes evanescent — there is no total-internal-reflection gap, one of the practical advantages of such media. The implementation adds one Newton re-projection step onto the contour, eliminating the accumulation of machine error." },
{ type: "h2", text: "2.3. The wavelength cascade and the resonance scale" },
{ type: "p", text: "Each reflection from an inclined wall jumps the wave vector along the hyperbola branch: |k| grows while the direction of the group velocity saturates towards the dispersion asymptote. This produces the wavelength cascade observed in the reference experiment: the wavelength along the route shortens from bounce to bounce until it reaches the smallest scale of the system — the unit cell of the metamaterial in the experiment, the grid spacing in the numerical model. The naive criterion for the attractor is phrased in terms of the resonance between the slope length s and the cone: s* = 1/√η; chapter 4 shows that the actual attractor window is noticeably narrower, with both boundaries universal in the variable u = s·√η." },
{ type: "h2", text: "2.4. Chambers and chirality" },
{ type: "p", text: "The main chamber of the study is a hexagon with vertical side walls and two shallow bottom slopes (s = 0.03 and 0.06 at y_v = 0.35); the deliberate left–right asymmetry of the slopes selects a single circulation sense of the attractor. For this dispersion the vertical walls are specular (k_{x} → −k_{x}, k_{y} conserved) and act as switches of the horizontal drift, while the slopes provide the cascade. The chirality of the closed route is measured by the index C — the net signed rotation of the tangent along the loop (in full turns); a simple convex loop yields |C| ≈ 1. The mirrored chamber gives birth to the mirrored route with the opposite C — the exact chiral complementarity verified by experiment E3." },

// ════════════════════════════════════════════ Chapter 3
{ type: "h1", text: "3. Ray model: experiments E1–E5" },
{ type: "h2", text: "3.1. The ray-billiard algorithm" },
{ type: "p", text: "The ray model is implemented in ray_billiard.py. A free flight moves the point along v_{g} to the nearest boundary intersection (an exact linear solution per edge, taking the nearest positive crossing). The reflection follows the Vieta-root law (2.4)–(2.5) with a Newton re-projection. Particular care is devoted to determinism: a hit at a vertex is handled by reflection off the bisector of the two adjacent normals (a rounded-defect model), and a free flight starts with a 10⁻⁹-scale offset along the inward normal. All rules are defined so that the Python and Julia implementations agree pointwise — a necessary condition for the cross-verification of chapter 8. Limit cycles are detected by repetition of bounce points with period m ≤ 100 and tolerance 10⁻⁶…10⁻⁷." },
{ type: "p", text: "The module self-tests (seven checks) include specularity of the isotropic reflection, conservation of dispersion and k_{t} under hyperbolic reflection, the group velocity pointing into the chamber, cone confinement, containment of rays inside the closed chamber, and the formation of closed loops in the trapezoid." },
{ type: "h2", text: "3.2. E1: the wavelength cascade" },
{ type: "p", text: "The full protocol is 24 rays × 1600 bounces in the hexagonal chamber at η = 100. The mean transient growth of the wave-vector magnitude per slope bounce is ×7.6 (maximum ×65); the convergence of the trajectory to the route is geometric, with a median exponent q = 0.992 (distances to the limit loop decay as q^{n}). The accumulated statistics of slope hits (E1_cascade_slope_hits.csv) show that before capture the cascade amplifies |k| by decades, while after capture the growth terminates at the grid limit — the numerical analogue of the cell termination." },
{ type: "fig", path: FIG + "/02_cascade.png", caption: "Fig. 3.1. E1. Left: |k| before slope bounces (first 10 rays, log scale) — geometric growth up to lock-in. Right: histogram of the geometric convergence exponent q; median 0.992." },
{ type: "h2", text: "3.3. E2: hyperbolic medium versus isotropic control" },
{ type: "p", text: "The control experiment separates the role of anisotropy from that of geometry: in the same chamber under the same initial conditions (24 rays) the hyperbolic medium captures 24 of 24 rays (fraction 1.00), the isotropic one — 0 of 24 (fraction 0.00). Captured trajectories collapse onto the common route; isotropic ones fill the chamber uniformly and chaotically. This is the direct demonstration that the attractor is an effect of the material, not of the shape." },
{ type: "fig", path: FIG + "/03_attractor_vs_control.png", caption: "Fig. 3.2. E2. Left: hyperbolic medium — 14 rays collapse onto the route (red). Right: isotropic control — the same initial conditions produce chaos without capture." },
{ type: "h2", text: "3.4. E3: chirality and mirror complementarity" },
{ type: "p", text: "The net chirality of the mirror pair of attractors (the original chamber plus the mirrored chamber with the mirrored initial condition) is zero to machine precision; the Hausdorff distance between the loops after mirroring is 0.0. In the symmetric chamber, attractors of both circulation senses coexist: the measured indices are C = ±0.4683, ±0.0317 and 0 — the direction is selected spontaneously by the launched wave. Chirality here is thus a property of the route inside the asymmetric chamber, not of the material: the medium is scalar, and mirror symmetry is broken by geometry alone." },
{ type: "fig", path: FIG + "/05_chirality.png", caption: "Fig. 3.3. E3. Original and mirrored chambers: closed routes and chirality indices; the pair sums to zero exactly." },
{ type: "h2", text: "3.5. E4: frequency invariance and ray density" },
{ type: "p", text: "The normalised map (k_{x}/K, k_{y}/K) is independent of K: reflections preserve the normalised direction. The check over 1201 bounces at K = 1 versus K = 7 gives a maximum deviation of 0.0 — the frequency invariance is exact, the attractor is broadband. The geometrical-acoustics analogue of the wave intensity — the ray-path density — exhibits a corridor with a contrast of ×5.47 against the background (E4c), predicting the band-averaged picture of chapter 5." },
{ type: "fig", path: FIG + "/07_ray_density.png", caption: "Fig. 3.4. E4c. Ray-path density (normalised): the attractor corridor stands out with a ×5.47 contrast; the route is shown in cyan." },
{ type: "h2", text: "3.6. E5: the phase diagram" },
{ type: "p", text: "The map of the lock-in fraction over the plane (slope length s, vertical-wall lower bound y_v) delineates a robust attractor phase at small s and a regular phase at steep slopes, where the cascade sweeps the rays into corners (runaway). This diagram is the numerical analogue of the «attractor phase transitions» of the reference study; its η-slice is systematically extended by the E6 scan (chapter 4)." },
{ type: "fig", path: FIG + "/04_phase_diagram.png", caption: "Fig. 3.5. E5. Phase diagram: the fraction of rays captured by the attractor over the (s, y_v) plane at η = 100." },
{ type: "h2", text: "3.7. Summary of the ray-level results" },
{ type: "table",
  caption: "Table 3.1. Key results of experiments E1–E5 (full protocol, η = 100).",
  headers: ["Observable", "Value", "Experiment"],
  colPct: [50, 30, 20],
  rows: [
    ["Attractor lock-in (hyperbolic / isotropic medium)", "**24/24 (1.00)** vs **0/24 (0.00)**", "E2"],
    ["Cascade of |k| per slope bounce (transient)", "mean **×7.6**, maximum ×65", "E1"],
    ["Geometric convergence to the route", "q = 0.992 (median)", "E1"],
    ["Mirror-pair chirality sum C + C′", "**0.0** (machine precision), Hausdorff 0.0", "E3"],
    ["Coexisting circulation senses", "C = ±0.4683, ±0.0317, 0", "E3"],
    ["Frequency invariance (K = 1 vs K = 7)", "maximum deviation **0.0**", "E4a"],
    ["Ray-density corridor contrast", "**×5.47**", "E4c"],
  ],
},

// ════════════════════════════════════════════ Chapter 4
{ type: "h1", text: "4. E6: anisotropy scan and the universality of the attractor window" },
{ type: "h2", text: "4.1. Scan setup" },
{ type: "p", text: "The ray scan E6a varies the two dimensionless controls — the slope length s and the anisotropy strength η: five values η ∈ {9, 16, 25, 100, 400}, twelve slopes s ∈ [0.005; 0.14] and an ensemble of 12 rays per (η, s) pair in the symmetric hexagonal chamber with y_v = 0.35. Two technical decisions matter. First, the bounce budget scales with η (500 for η ≤ 100 and 2500 for η = 400), because both the attractor period and the transient length grow with anisotropy — with a fixed budget the large-η runs appeared «non-capturing», an artifact discovered and removed in an early version of the scan. Second, the lock fraction is measured by the limit-cycle detector with the tolerance 10⁻⁶ identical for all η." },
{ type: "p", text: "The wave scan E6b solves the anisotropic Helmholtz equation (chapter 5) at η ∈ {4, 9, 16, 36} with the fixed chamber, a directional source and band averaging over four frequencies around f = 9." },
{ type: "h2", text: "4.2. Result: the attractor window is universal in u = s·√η" },
{ type: "p", text: "The lock fraction as a function of s is non-monotonic for every η: for slopes that are too shallow the cascade is too weak and the rays do not organise; for slopes that are too steep the route is destroyed. The remarkable fact is that BOTH boundaries of this window collapse onto the single variable u = s·√η: the smoothed capture curves for all five η yield the lower boundary u₁ = 0.176 ± 0.041 and the upper boundary u₂ = 0.490 ± 0.084 (Fig. 4.1a, b; Table 4.1). The lower boundary expresses the necessity of a cascade exceeding the cone width ~1/√η; the upper one — the degradation of the Vieta amplification as the slope approaches the dispersion asymptote." },
{ type: "p", text: "This refines the naive resonance criterion of chapter 2: the formal scale s* = 1/√η (u = 1) OVERESTIMATES the window — in practice the attractor disappears already at u ≈ 0.5, i.e. the slopes must be noticeably shallower than the asymptote resonance requires. The agreement with the E5 phase diagram (a boundary at s ≈ 0.06–0.08 for η = 100, i.e. u ≈ 0.6–0.8 in the coarse slice) is restored once smoothing and the coarser E5 grid are taken into account." },
{ type: "fig", path: FIG + "/10_eta_scan.png", caption: "Fig. 4.1. E6. (a) Collapse of the five-η capture curves in the variable u = s·√η; the green band is the fitted attractor window, the dotted line — the naive resonance u = 1. (b) Individual windows of the five η in the variable u; solid lines and grey bands — the means and standard deviations of u₁, u₂. (c) The channeling anisotropy H(η) of the band-averaged intensity: growth from the isotropic baseline 0.5 with saturation at H ≈ 0.85." },
{ type: "table",
  caption: "Table 4.1. Attractor windows per η (0.5-crossings of the smoothed capture curve).",
  headers: ["η", "Lower boundary u₁", "Upper boundary u₂", "Peak lock fraction"],
  colPct: [22, 26, 26, 26],
  rows: [
    ["9", "0.135", "0.39", "1.00"],
    ["16", "0.12", "0.56", "1.00"],
    ["25", "0.225", "0.50", "1.00"],
    ["100", "0.20", "0.60", "0.92"],
    ["400", "0.20", "0.40", "0.92"],
    ["**pooled**", "**0.176 ± 0.041**", "**0.490 ± 0.084**", "—"],
  ],
},
{ type: "h2", text: "4.3. Wave level: field channeling" },
{ type: "p", text: "The band-averaged |E|² maps at η = 4, 9, 16, 36 demonstrate a morphological transition: from nearly isotropic speckle at η = 4 to narrow vertical channels at η = 36 — the wave picture is «locked» into the cone the more rigidly, the stronger the anisotropy. The quantitative measure is the spectral anisotropy H of the intensity: the share of the |E|²-pattern spectral weight at |q_{x}| > |q_{y}| (channels along y) over the total weight at q > 3. H grows with η from 0.779 (η = 4) to 0.866 (η = 16) with saturation at ≈ 0.85 (Fig. 4.1c); the isotropic baseline for comparison is 0.5. The saturation reflects the finite angular bandwidth of the source and scattering off the cavity: the channeling cannot become ideal even as η → ∞." },

// ════════════════════════════════════════════ Chapter 5
{ type: "h1", text: "5. Wave model I: frequency domain (Helmholtz)" },
{ type: "h2", text: "5.1. Setup and discretisation" },
{ type: "p", text: "The frequency model solves the anisotropic Helmholtz equation for the out-of-plane field E = E_z inside the polygonal chamber with a perfectly conducting boundary E|_wall = 0:" },
{ type: "formula", num: "5.1", markup: "(1/*μ*_{y}) *E*_{xx} + (1/*μ*_{x}) *E*_{yy} + *k*_{0}^{2}(1 + *iγ*)*E* = *S*," },
{ type: "p", text: "with μ_x = 1, μ_y = −η and a weak loss γ = 10⁻³ (regularisation of resonances). The discretisation is five-point; in matrix form it is a complex sparse system solved by sparse LU factorisation (scipy). The plane-wave dispersion of this problem coincides with (2.1), so the wave and ray models describe the same medium." },
{ type: "h2", text: "5.2. Directional source and band averaging" },
{ type: "p", text: "The E4 protocol uses two devices without which the route drowns in the resonant background of the frequency-domain picture. The first is a directional source: a Gaussian beam patched with the phase gradient of the locked ray direction, so that energy is injected directly onto the route. The second is band averaging: |E|² is averaged over four frequencies inside each band (f = 6, 9, 14); the standing-wave fringes shift with frequency while the geometric footprint of the attractor is invariant, so the averaging reveals the route and simultaneously demonstrates its broadband character. Without averaging the resonant background can mask the corridor completely — the same phenomenon dictated the choice of the pulsed protocol in the time domain (chapter 6)." },
{ type: "fig", path: FIG + "/06_wave_maps.png", caption: "Fig. 5.1. Band-averaged |E|² in three frequency bands (directional source; η = 9, 384×384 grid). The ray route is shown in cyan." },
{ type: "h2", text: "5.3. Observations" },
{ type: "p", text: "The inter-band correlations of the band-averaged maps are positive but moderate (coefficients 0.10–0.15): a common geometric footprint is present, yet the fine cascade structure is re-stamped at every frequency. The spatial resolvability of the cascade is limited by the grid — the numerical analogue of the cell termination; in chapter 6 this limit is promoted to a physical parameter of the model." },
];
