# ━━ Cascade Palette (auto-generated by design_engine.py palette-cascade) ━━
from reportlab.lib import colors

# XL tier: backgrounds (area > 50%, S ≤ 0.08)
PAGE_BG       = colors.HexColor('#f1f0ef')
SECTION_BG    = colors.HexColor('#f2f1f0')

# L tier: surfaces (area 20-50%, S ≤ 0.15)
CARD_BG       = colors.HexColor('#e8e7e4')
TABLE_STRIPE  = colors.HexColor('#eeedeb')

# M tier: structural fills (area 5-20%, S ≤ 0.30)
HEADER_FILL   = colors.HexColor('#504933')
COVER_BLOCK   = colors.HexColor('#867b5a')

# S tier: edges & icons (area 1-5%, S ≤ 0.50)
BORDER        = colors.HexColor('#cfcab8')
ICON          = colors.HexColor('#8c7e52')

# XS tier: emphasis (area < 1%, S ≤ 0.75)
ACCENT        = colors.HexColor('#87702a')
ACCENT_2      = colors.HexColor('#3a95b4')

# Typography
TEXT_PRIMARY   = colors.HexColor('#1c1c1a')
TEXT_MUTED     = colors.HexColor('#78766f')

# Semantic (low-saturation, area-appropriate)
SEM_SUCCESS   = colors.HexColor('#46875c')
SEM_WARNING   = colors.HexColor('#a18347')
SEM_ERROR     = colors.HexColor('#92453e')
SEM_INFO      = colors.HexColor('#466a8e')
